apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-master
  template:
    metadata:
      labels:
        app: hadoop-master
    spec:
      containers:
      - name: hadoop-master
        image: amnrz/hadoop-master:version1
        command: ["/bin/bash", "-c", "service ssh start && hdfs namenode -format && hadoop-daemon.sh start namenode && hadoop-daemon.sh start resourcemanager && yarn daemons && tail -f /dev/null"]
        ports:
        - containerPort: 5009
        - containerPort: 8098
        - containerPort: 19888